### ISSUE TITLE
Read ini file process

### ISSUE THREAD

**Issue by djibb** [thelondonsmiths/Solex_ser_recon_EN#13]
Actually, here are scenarii having SHG ini file.
Scenario I : 
1) launch from first time SHG_main.py from fresh location : 
-> attempt to read ini file that doesn't exist
-> save ini file
2) Load a new file : 
-> attempt to read ini file -> OK
___ that's a normal behaviour from a fresh new directory

Scenario II : 
Launch from first time SHG_main.py: 
-> read SHG.ini from where SHG_main.py was launched
-> ERROR -> make a new SHG.ini when computing things.
So, SHG.ini file is not re-read even if existing.

Proposition (don't know if possible with simple_gui): 
launch a read_ini and a refresh of GUI when a new location is set.

NB : this is fixed for CLI (in my pull request). SHG.ini is read if existing. (it's easier with cli because path is still done)

**Comment by thelondonsmiths** [comment]
Thanks for this analysis. I only ever really use the GUI so I don't have much experience with the CLI. On holiday now but will investigate when I'm back.

**Comment by thelondonsmiths** [comment]
Your pull request accepted so I assume the issue is resolved.
