### ISSUE TITLE
read SHG.ini... need to reshape ?

### ISSUE THREAD

**Issue by djibb** [thelondonsmiths/Solex_ser_recon_EN#15]
Hi, 
I've adding some option (in my git fork) from cli.
But... it's not easy, because there are some options that are in options{} variable, but not in ini files, it's non documented, so which is in options, which is not etc.
I think ini file should be a copy of options{} + serfiles path.

The + : readable, auto-documented, editable, copy of heart of software (JSON file)
The - : break compatibility with <=3.5 version 

To be honest, I don't think lots of people re-use SHG.ini with old SER files. So, this can be almost without any consequences. 

So, i will not produce a pull request on it, but wait your reflexion on this, and begin to code a JSON extraction.

**Comment by djibb** [comment]
So... I've done this here : https://github.com/djibb/Solex_ser_recon_EN/tree/SHG_INI_JSON
- INI file is now called SHG_V2.ini and is on JSON readable format
- it handles cli parameters
- when choosing a file, INI file is read (if existing) and UI updated with INI values.
So if it's OK for you, I will open a pull request.

**Comment by thelondonsmiths** [comment]
I have now implemented this. It makes some things simpler. Thanks for the suggestion.
