### ISSUE TITLE
CLI options are crushed by .txt options file

### ISSUE THREAD

**Issue by djibb** [thelondonsmiths/Solex_ser_recon_EN#16]
when user use CLI, he wants exactly what he writes as options.
If a txt fil is present, read_ini() is called after reading cli argument, so cli options are crushed  by txt file.
To avoid thi behaviour : 
-> last line, remove 'cli=True'
-> near line number 300 : remove "if cli" block...

**Comment by thelondonsmiths** [comment]
My latest commit resolves this, thanks for noticing it
