### ISSUE TITLE
Corrected images are missing parts!

### ISSUE THREAD

**Issue by igeek1024** [thelondonsmiths/Solex_ser_recon_EN#23]
console:
solex_util.py:288: RuntimeWarning: divide by zero encountered in log
solex_util.py:304: RuntimeWarning: divide by zero encountered in log
solex_util.py:323: RuntimeWarning: divide by zero encountered in log
solex_util.py:423: RuntimeWarning: invalid value encountered in cast

Corrected images:
![image](https://github.com/thelondonsmiths/Solex_ser_recon_EN/assets/77236124/9eacda54-44c6-4266-8298-b0d0cc671045)
Uncorrected image:
![image](https://github.com/thelondonsmiths/Solex_ser_recon_EN/assets/77236124/07961474-fa38-4923-b451-f594e7e70e8b)

**Comment by thelondonsmiths** [comment]
It looks like the raw data has one or more data points that have a zero. Which software are you using? FireCapture, SharpCap? First, check to make sure that in the acquisition software there is an offset. It is usually the default (with FireCapture I believe the default is an offset of 8). Did you use the "stubborn transversalium" feature? If so, try to turn this off.

**Comment by igeek1024** [comment]
I am using ASI Studio, Problem solved by increasing offset value, thank you.

**Comment by igeek1024** [comment]
I am using ASI Studio, Problem solved by increasing offset value, thank you.
