### ISSUE TITLE
Issue on ellipse edge detection

### ISSUE THREAD

**Issue by Vdesnoux** [thelondonsmiths/Solex_ser_recon_EN#6]
Still not robust on calcium scan. Would suggest you revert to original solex-recon algorithm
![image](https://user-images.githubusercontent.com/81253361/128193018-fe9a9f2f-a550-46f8-bbd2-9dc77b6cab7d.png)

**Comment by thelondonsmiths** [comment]
Interesting. Is it an edge detection issue because the Calcium image is darker?

**Comment by Vdesnoux** [comment]
I guess yes, also the gradient is different.

**Comment by mconsidine** [comment]
Fyi, I was looking at the lsq-ellipse code and note they use arctan versus arctan2.  There may be a good reason for that, but I believe the former can have problems with  angles that end up in other quadrants.  In my case I have that issue and the existing code has been a challenge.  I can get around it with a version of fit ellipse and some sign changes.  But I think my way is a kludge and I'm not satisfied with it.With the frames I fed the code, it seemed to include the top flat edge as a border to the ellipse fitting routine.  Which yielded an odd result to say the least.More when I can investigate,MattOn Aug 4, 2021 12:37 PM, valerie desnoux ***@***.***> wrote:
I guess yes, also the gradient is different.

**Comment by thelondonsmiths** [comment]
We have pushed a potential fix for this issue. Could you re-run the same calcium file and see if the result is better?

**Comment by thelondonsmiths** [comment]
I ran the most recent version on some calcium files and the behaviour was now normal. If you see the issue still, please let us know.
