### ISSUE TITLE
Tilt correction

### ISSUE THREAD

**Issue by Vdesnoux** [thelondonsmiths/Solex_ser_recon_EN#7]
Tilt correction is not a rotation. Sun image generated are not physically correct.

**Comment by thelondonsmiths** [comment]
Do you mean it should be a pure shear transformation with no rotation?

**Comment by Vdesnoux** [comment]
yes. I think you shall stick the algorithms principle you have in solex_recon. It may be slow but at least it is the reference and has been test with a lot of different scans and configuration between Christian and I. Also, it is "approved" by Christian. I can update it and you can improve the GUI but It is very important we keep the core processing under control.

**Comment by mconsidine** [comment]
I'll revert the core process of my "Digital_SHG" to Valerie's.  It may take awhile before I can do that as Stellafane is getting underway.On Aug 4, 2021 12:40 PM, valerie desnoux ***@***.***> wrote:
yes. I think you shall stick the algorithms principle you have in solex_recon. It may be slow but at least it is the reference and has been test with a lot of different scans and configuration between Christian and I. Also, it is "approved" by Christian. I can update it and you can improve the GUI but It is very important we keep the core processing under control.

**Comment by thelondonsmiths** [comment]
This has been resolved in the latest commit using a simple adjustment to the correction matrix. The top-right element of the matrix is now forced to zero, making it a pure shear by definition. (This is achieved using an "un-rotation  angle" theta.) For an undistorted image the correction matrix is a unity matrix.
