### ISSUE TITLE
Solex_recon code block error?

### ISSUE THREAD

**Issue by mconsidine** [thelondonsmiths/Solex_ser_recon_EN#9]
I believe there is an error in lines 229-233 of Solex_recon, which I have brought to Valerie's attention.

Imagine that c=10.  Then a median is calculated based on indices c =3 through 16.  That result is stored at index 10 in img.  Then with c=11 a new median is calculated, and this now includes the median just calculated for c=10.

I believe the intent was to do a median calc on a copy of img, with the result stored in img, so that the median calcs were always uncorrupted by prior calcs.

Matt

**Comment by thelondonsmiths** [comment]
Thanks, I have changed the code accordingly.
